language: ruby
rvm:
- 2.1.0

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database bonus_test;' -U postgres
  - cp config/database.travis.yml config/database.yml

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
